"""Measure Direct HTTP stream-to-disk I/O without opening a network socket.

The benchmark loads the real built-in provider and replaces only its DNS and
URL opener boundaries inside an isolated module instance.  The provider still
validates an explicit HTTPS file URL, streams to ``.part``, hashes the payload,
checks the expected SHA-256, and atomically renames the completed file.

All generated bytes live under a dedicated root outside the repository and
are removed before the report is returned.  Evidence must also be written
outside the repository so benchmark output cannot pollute source state.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import math
import platform
from pathlib import Path
import sys
import time
import tracemalloc
from types import ModuleType
from typing import Any

from core.version import CORE_VERSION
from tools import g39_baseline
from tools.source_fingerprint import source_fingerprint, source_revision
from tools.startup_baseline import write_report


_SCHEMA_VERSION = 1
_WORKLOAD_ID = "direct-http-synthetic-stream-v1"
_SYNTHETIC_URL = "https://downloads.example.org/benchmark.mkv"
_SYNTHETIC_BYTE = b"\xa5"
_DEFAULT_PAYLOAD_BYTES = 32 * 1024 * 1024
_DEFAULT_CHUNK_SIZES = (256 * 1024, 1024 * 1024, 4 * 1024 * 1024)
_MAX_PAYLOAD_BYTES = 256 * 1024 * 1024
_MAX_CHUNK_BYTES = 8 * 1024 * 1024
_MAX_TRANSIENT_WRITE_BYTES = 4 * 1024**3
_MAX_READ_CALLS = 2_000_000


class _SyntheticHeaders:
    def __init__(self, length: int) -> None:
        self._length = length

    def get(self, key: str) -> str | None:
        if key.casefold() == "content-length":
            return str(self._length)
        return None


class _SyntheticResponse:
    def __init__(self, payload_bytes: int) -> None:
        self._payload_bytes = payload_bytes
        self._offset = 0
        self.status = 200
        self.headers = _SyntheticHeaders(payload_bytes)
        self.read_sizes: list[int] = []

    def __enter__(self) -> _SyntheticResponse:
        return self

    def __exit__(self, *_args: object) -> None:
        return None

    def geturl(self) -> str:
        return _SYNTHETIC_URL

    def read(self, size: int) -> bytes:
        if not isinstance(size, int) or size <= 0:
            raise AssertionError("provider requested an invalid read size")
        self.read_sizes.append(size)
        remaining = self._payload_bytes - self._offset
        amount = min(size, max(0, remaining))
        self._offset += amount
        return _SYNTHETIC_BYTE * amount


class _SyntheticOpener:
    def __init__(self, payload_bytes: int) -> None:
        self._payload_bytes = payload_bytes
        self.responses: list[_SyntheticResponse] = []
        self.opened_urls: list[str] = []

    def open(self, request: object, timeout: int) -> _SyntheticResponse:
        if timeout != 30:
            raise AssertionError("provider changed its bounded network timeout")
        url = str(getattr(request, "full_url", ""))
        if url != _SYNTHETIC_URL:
            raise AssertionError("provider attempted an unexpected URL")
        self.opened_urls.append(url)
        response = _SyntheticResponse(self._payload_bytes)
        self.responses.append(response)
        return response


def _load_provider(repository: Path) -> ModuleType:
    path = repository / "mod" / "builtin" / "direct-http" / "provider.py"
    if not path.is_file() or path.is_symlink():
        raise FileNotFoundError("built-in Direct HTTP provider is unavailable")
    spec = importlib.util.spec_from_file_location(
        "_mediamanager_direct_http_io_baseline_provider",
        path,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("Direct HTTP provider could not be loaded")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _stats(values: list[int | float], *, digits: int | None = None) -> dict[str, Any]:
    if not values:
        raise ValueError("benchmark statistics require at least one sample")

    def normalized(value: int | float) -> int | float:
        if digits is None:
            return int(value)
        return round(float(value), digits)

    return {
        "min": normalized(min(values)),
        "p50": normalized(g39_baseline.nearest_rank(values, 0.50)),
        "p95": normalized(g39_baseline.nearest_rank(values, 0.95)),
        "max": normalized(max(values)),
    }


def _synthetic_sha256(payload_bytes: int) -> str:
    digest = hashlib.sha256()
    remaining = payload_bytes
    block = _SYNTHETIC_BYTE * min(payload_bytes, 1024 * 1024)
    while remaining:
        amount = min(len(block), remaining)
        digest.update(block[:amount])
        remaining -= amount
    return digest.hexdigest()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while block := handle.read(1024 * 1024):
            digest.update(block)
    return digest.hexdigest()


def _run_sample(
    provider: ModuleType,
    sample_root: Path,
    *,
    payload_bytes: int,
    chunk_bytes: int,
    expected_sha256: str,
) -> dict[str, int | float]:
    sample_root.mkdir()
    opener = _SyntheticOpener(payload_bytes)
    host_validation_calls = 0
    progress_events = 0

    def validate_host(_host: str) -> None:
        nonlocal host_validation_calls
        host_validation_calls += 1

    def record_event(message: dict[str, Any]) -> None:
        nonlocal progress_events
        if message.get("type") == "progress":
            progress_events += 1

    provider._STREAM_CHUNK_BYTES = chunk_bytes
    provider._global_host = validate_host
    provider.build_opener = lambda *_handlers: opener
    provider.emit = record_event

    if tracemalloc.is_tracing():
        raise RuntimeError("tracemalloc is already active")
    tracemalloc.start()
    started_at = time.perf_counter_ns()
    cpu_started_at = time.process_time_ns()
    try:
        result = provider.download(
            {
                "url": _SYNTHETIC_URL,
                "output_dir": str(sample_root),
                "provider_options": {"expected_sha256": expected_sha256},
            }
        )
        cpu_ns = time.process_time_ns() - cpu_started_at
        elapsed_ns = time.perf_counter_ns() - started_at
        _, memory_peak_bytes = tracemalloc.get_traced_memory()
    finally:
        tracemalloc.stop()

    output = Path(result)
    if output.parent != sample_root.resolve() or output.name != "benchmark.mkv":
        raise RuntimeError("Direct HTTP benchmark output escaped its sample root")
    if output.stat().st_size != payload_bytes:
        raise RuntimeError("Direct HTTP benchmark output size does not match")
    if _file_sha256(output) != expected_sha256:
        raise RuntimeError("Direct HTTP benchmark output digest does not match")
    if len(opener.responses) != 1 or opener.opened_urls != [_SYNTHETIC_URL]:
        raise RuntimeError("Direct HTTP benchmark did not use its synthetic opener")
    response = opener.responses[0]
    if not response.read_sizes or set(response.read_sizes) != {chunk_bytes}:
        raise RuntimeError("Direct HTTP provider ignored the selected chunk size")
    if host_validation_calls != 2:
        raise RuntimeError("Direct HTTP URL validation path changed unexpectedly")
    expected_events = math.ceil(payload_bytes / chunk_bytes)
    if progress_events != expected_events:
        raise RuntimeError("Direct HTTP progress event count is inconsistent")

    seconds = elapsed_ns / 1_000_000_000
    return {
        "elapsed_ms": elapsed_ns / 1_000_000,
        "cpu_ms": cpu_ns / 1_000_000,
        "throughput_mib_s": payload_bytes / (1024**2) / seconds,
        "tracemalloc_peak_bytes": memory_peak_bytes,
        "progress_events": progress_events,
    }


def _validate_workload(
    *,
    warmups: int,
    iterations: int,
    payload_bytes: int,
    chunk_sizes: tuple[int, ...],
) -> int:
    if not isinstance(warmups, int) or isinstance(warmups, bool) or not 0 <= warmups <= 5:
        raise ValueError("warmups must be between 0 and 5")
    if (
        not isinstance(iterations, int)
        or isinstance(iterations, bool)
        or not 1 <= iterations <= 20
    ):
        raise ValueError("iterations must be between 1 and 20")
    if (
        not isinstance(payload_bytes, int)
        or isinstance(payload_bytes, bool)
        or not 1 <= payload_bytes <= _MAX_PAYLOAD_BYTES
    ):
        raise ValueError("payload_bytes must be between 1 byte and 256 MiB")
    if not chunk_sizes:
        raise ValueError("chunk_sizes must not be empty")
    if len(chunk_sizes) > 8:
        raise ValueError("chunk_sizes must contain at most 8 entries")
    if len(set(chunk_sizes)) != len(chunk_sizes):
        raise ValueError("chunk_sizes must not contain duplicates")
    for chunk_bytes in chunk_sizes:
        if (
            not isinstance(chunk_bytes, int)
            or isinstance(chunk_bytes, bool)
            or not 1 <= chunk_bytes <= _MAX_CHUNK_BYTES
        ):
            raise ValueError("each chunk size must be between 1 byte and 8 MiB")
    rounds = warmups + iterations
    transient_bytes = payload_bytes * rounds * len(chunk_sizes)
    if transient_bytes > _MAX_TRANSIENT_WRITE_BYTES:
        raise ValueError("benchmark transient writes exceed the 4 GiB limit")
    read_calls = sum(math.ceil(payload_bytes / size) for size in chunk_sizes) * rounds
    if read_calls > _MAX_READ_CALLS:
        raise ValueError("benchmark synthetic read count exceeds the safety limit")
    return transient_bytes


def run_baseline(
    *,
    repository_root: Path,
    temp_root: Path | None = None,
    warmups: int = 2,
    iterations: int = 7,
    payload_bytes: int = _DEFAULT_PAYLOAD_BYTES,
    chunk_sizes: tuple[int, ...] = _DEFAULT_CHUNK_SIZES,
    include_source_identity: bool = True,
) -> dict[str, Any]:
    """Run the bounded synthetic workload and return a serializable report."""

    chunk_sizes = tuple(chunk_sizes)
    transient_bytes = _validate_workload(
        warmups=warmups,
        iterations=iterations,
        payload_bytes=payload_bytes,
        chunk_sizes=chunk_sizes,
    )
    repository = repository_root.resolve()
    benchmark_root = g39_baseline.validate_temp_root(
        g39_baseline.default_temp_root() if temp_root is None else temp_root,
        repository,
    )
    provider = _load_provider(repository)
    expected_sha256 = _synthetic_sha256(payload_bytes)
    attempt, token = g39_baseline._create_owned_attempt(benchmark_root)
    recorded: dict[int, list[dict[str, int | float]]] = {
        size: [] for size in chunk_sizes
    }
    sample_number = 0
    cleanup_succeeded = False
    try:
        for round_index in range(warmups + iterations):
            ordered_sizes = (
                chunk_sizes if round_index % 2 == 0 else tuple(reversed(chunk_sizes))
            )
            for chunk_bytes in ordered_sizes:
                sample_number += 1
                sample_root = attempt / f"sample-{sample_number:03d}"
                sample = _run_sample(
                    provider,
                    sample_root,
                    payload_bytes=payload_bytes,
                    chunk_bytes=chunk_bytes,
                    expected_sha256=expected_sha256,
                )
                g39_baseline._cleanup_sample(sample_root, attempt)
                if round_index >= warmups:
                    recorded[chunk_bytes].append(sample)
    finally:
        g39_baseline._remove_owned_attempt(attempt, token)
        cleanup_succeeded = not attempt.exists()

    results: list[dict[str, Any]] = []
    for chunk_bytes in chunk_sizes:
        samples = recorded[chunk_bytes]
        results.append(
            {
                "chunk_bytes": chunk_bytes,
                "samples": len(samples),
                "elapsed_ms": _stats(
                    [sample["elapsed_ms"] for sample in samples], digits=3
                ),
                "cpu_ms": _stats(
                    [sample["cpu_ms"] for sample in samples], digits=3
                ),
                "throughput_mib_s": _stats(
                    [sample["throughput_mib_s"] for sample in samples], digits=3
                ),
                "tracemalloc_peak_bytes": _stats(
                    [sample["tracemalloc_peak_bytes"] for sample in samples]
                ),
                "progress_events": _stats(
                    [sample["progress_events"] for sample in samples]
                ),
            }
        )

    if include_source_identity:
        source = {
            "core_version": CORE_VERSION,
            "fingerprint_sha256": source_fingerprint(repository),
            "revision": source_revision(repository),
        }
    else:
        source = {
            "core_version": "not-recorded",
            "fingerprint_sha256": "not-recorded",
            "revision": "not-recorded",
        }
    return {
        "schema_version": _SCHEMA_VERSION,
        "result": "BASELINE_RECORDED",
        "source": source,
        "environment": {
            "python": platform.python_version(),
            "implementation": platform.python_implementation(),
            "os": platform.system(),
            "os_release": platform.release(),
            "machine": platform.machine(),
        },
        "workload": {
            "id": _WORKLOAD_ID,
            "warmups": warmups,
            "iterations": iterations,
            "payload_bytes": payload_bytes,
            "chunk_sizes": list(chunk_sizes),
            "expected_transient_write_bytes": transient_bytes,
        },
        "results": results,
        "safety": {
            "network_allowed": False,
            "real_url_opened": False,
            "user_data_read": False,
            "provider_security_policy_changed": False,
            "owned_attempt_removed": cleanup_succeeded,
        },
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--temp-root", type=Path)
    parser.add_argument("--warmups", type=int, default=2)
    parser.add_argument("--iterations", type=int, default=7)
    parser.add_argument("--payload-mib", type=int, default=32)
    parser.add_argument(
        "--chunk-kib",
        type=int,
        action="append",
        help="Repeat to compare chunk sizes (default: 256, 1024, 4096 KiB).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parsed = _parser().parse_args(argv)
    repository = Path(__file__).resolve().parents[1]
    chunk_sizes = tuple(
        size * 1024 for size in (parsed.chunk_kib or (256, 1024, 4096))
    )
    try:
        report = run_baseline(
            repository_root=repository,
            temp_root=parsed.temp_root,
            warmups=parsed.warmups,
            iterations=parsed.iterations,
            payload_bytes=parsed.payload_mib * 1024 * 1024,
            chunk_sizes=chunk_sizes,
        )
        output = write_report(report, parsed.output, repository)
    except (OSError, RuntimeError, ValueError) as error:
        print(f"Direct HTTP I/O baseline failed: {error}", file=sys.stderr)
        return 2
    print(f"Direct HTTP I/O baseline written: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
